### ISSUE TITLE
Sass for Woocommerce 3.x inclusion into starter theme.

### ISSUE THREAD

**Issue by bradfranklin** [claudiosmweb/woocommerce-sass#4]
Googling for a while now. Any chance you have an updated branch which supports the newer Woocommerce 3.x plugin?

Thanks in advance for posting your code. Any suggestions greatly appreciated.

**Comment by claudiosanches** [comment]
Just copy the files from WooCommerce 3.x.
As I say on this repository description:

![screenshot from 2017-08-08 21-56-50](https://user-images.githubusercontent.com/1264099/29100813-83fea32c-7c84-11e7-8b21-e9b7b49b357b.png)
